"""Create videos table

Revision ID: b22cbce1de06
Revises: 55b2b1372b82
Create Date: 2024-08-14 05:58:59.084860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22cbce1de06'
down_revision = '55b2b1372b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('traduccion', sa.Text(), nullable=True),
    sa.Column('favoritos', sa.Boolean(), nullable=True),
    sa.Column('video', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
